Re-enable sticker feature
ubports/messaging-app pull request #266
Opened 2021-01-25 13:32 UTC by lduboeuf

Some parts were already existing but not fully usable. Rewrite that feature an make it available in conversation view, 
see: https://forums.ubports.com/topic/5470/messaging-app-stickers-feature for UI rendering

2021-02-27 23:18 UTC, lduboeuf commented
should be a feature that can be toggled off in settings

2021-05-25 19:38 UTC, UniversalSuperBox requested changes
Only one question, but also don't forget to add your copyright!

2021-05-25 19:38 UTC, UniversalSuperBox commented on src/qml/Stickers/StickersPicker.qml
> +        onCountChanged: console.log('sps count', count);
Are the console.log's in this file still needed, or were they only for your testing?

2021-05-31 21:17 UTC, UniversalSuperBox approved these changes

2021-05-31 21:17 UTC, merged